name: covid19
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Used to launch URLs
  url_launcher: ^6.0.2
  # Used to handler http requests
  dio: ^3.0.9
  # Used to handler translations
  intl_utils: ^1.3.0
  # Used to aply the shimme effect
  shimmer: ^1.1.2
  # Used to get more fonts
  google_fonts: ^1.1.2
  # Used to build simple animations
  simple_animations: ^2.2.1
  # Used to get informations about the user's device
  device_info: ^1.0.0
  # Used to custom the louncher icon
  flutter_launcher_icons: ^0.8.1
  # Used for the bottom navigation bar
  bubble_bottom_bar: ^1.2.0
  # Used to set SVG images
  flutter_svg: ^0.19.3
  # Used to format numbers
  intl: ^0.16.1
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  # Used to refresh the page
  liquid_pull_to_refresh: ^2.0.0
  # Used to cache the data
  cached_network_image: ^2.2.0+1
  # Used to preview links
  flutter_link_preview: ^1.5.6
  # Used to copy to clipboard
  clipboard: ^0.1.2+8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon_app.png"

flutter:

  uses-material-design: true

  assets:
    - assets/images/virus.svg
    - assets/images/success.svg
    - assets/images/death.svg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
